- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    
- hosts: CouchDB
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true

  roles:
    - role: db-common
    - role: db-volume
    - role: db-docker
    - role: db-couchdb
    - role: db-cluster
    - role: db-harvest
    - role: db-website
