# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: db-vol-4-1
    vol_size: 20
  - vol_name: db-vol-4-2
    vol_size: 20


# Security group
security_groups:
  - name: demo_ssh
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: db_1
    description: "Couch DB requires 5984"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: db_2
    description: "Couch DB requires 4369"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: db_3
    description: "Couch DB requires 9100-9200"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: website
    description: "react web app needs port 3000"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: db3
    volumes: ['db-vol-4-1', 'db-vol-4-2']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: ccc
instance_flavor: uom.mse.1c4g
