---
- name: Pip install docker
  become: yes
  pip:
    name:
      - docker
      - docker-compose
    state: latest
# pip install docker

- name: Create couchdb directory
  tags: 'couchdb'
  become: yes
  file:
    path: "{{ dbdir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'couchdb'
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ dbdir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'couchdb'
  become: yes
  docker_compose:
    project_src: "{{ dbdir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always
